from alpaca_secrets import APCA_API_KEY_ID, APCA_API_SECRET_KEY, APCA_API_BASE_URL

API_KEY = APCA_API_KEY_ID
API_SECRET = APCA_API_SECRET_KEY
API_BASE_URL = APCA_API_BASE_URL
SYMBOL = "TSLA"
QTY = 10
STOP_LOSS_PCT = 0.01
SHORT_WINDOW = 25
LONG_WINDOW = 40
ADX_THRESHOLD = 30
T_PERIOD = 14
TIMEFRAME_MINUTES = 1