from alpaca_secrets import APCA_API_KEY_ID, APCA_API_SECRET_KEY, APCA_API_BASE_URL

API_KEY = APCA_API_KEY_ID
API_SECRET = APCA_API_SECRET_KEY
API_BASE_URL = APCA_API_BASE_URL

# Parâmetros da estratégia
SYMBOL = "ETH/USD"
QTY = 1
SHORT_WINDOW = 7
LONG_WINDOW = 30
ADX_THRESHOLD = 15
BUFFER_PCT = 0.001  # 0.1%
STOP_LOSS_PCT = 0.01
T_PERIOD = 14
TIMEFRAME_MINUTES = 1
