from alpaca_secrets import APCA_API_KEY_ID, APCA_API_SECRET_KEY, APCA_API_BASE_URL

API_KEY = APCA_API_KEY_ID
API_SECRET = APCA_API_SECRET_KEY
API_BASE_URL = APCA_API_BASE_URL

SYMBOL = "ETH/USD"
QTY = 0.1
SHORT_WINDOW = 10
LONG_WINDOW = 100
BUFFER_PCT = 0.000
TIMEFRAME_MINUTES = 1
