from alpaca_secrets import APCA_API_KEY_ID, APCA_API_SECRET_KEY, APCA_API_BASE_URL

API_KEY = APCA_API_KEY_ID
API_SECRET = APCA_API_SECRET_KEY
API_BASE_URL = APCA_API_BASE_URL

# Parâmetros da estratégia
SYMBOL = "IAU"
QTY = 10
WINDOW = 50
THRESHOLD = 1
STOP_LOSS_PCT = 0.01
TIMEFRAME_MINUTES = 1
